spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  graphql:
    http:
      path: /api/v1/graphql
    graphiql:
      enabled: true
      path: /api/v1/graphiql

server:
  port: ${PORT:8082}

resend:
  api-key: ${RESEND_API_KEY}
  from: ${MAIL_FROM:andrey.evtukh@gmail.com}

sender:
  api-token: ${SENDER_API_TOKEN}
  from-email: ${MAIL_FROM}
  from-name: ${MAIL_FROM_NAME:Andrey Evtukh}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

app:
  verification-code-ttl-minutes: 5