CREATE TABLE IF NOT EXISTS verification_codes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)             NOT NULL,
    code          VARCHAR(10)              NOT NULL,
    type          VARCHAR(30)              NOT NULL,
    username      VARCHAR(255)             NOT NULL,
    password_hash VARCHAR(255)             NOT NULL,
    expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    used          BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);